### ISSUE TITLE
[demoing-storybook] webpack config not found in version 0.4.1

### ISSUE THREAD

**Issue by blikblum** [open-wc/open-wc#931]
After upgrading to 0.4.1 i'm getting the following error when running storybook script:

Error: Cannot find module '@open-wc/demoing-storybook/default-storybook-webpack-config.js'

I checked and there's no default-storybook-webpack-config.js in package

**Comment by Westbrook** [comment]
This has been removed as per https://github.com/open-wc/open-wc/blob/master/packages/demoing-storybook/MIGRATION.md#removed-default-storybook-webpack-configjs 

Please follow the instructions to ensure your migration from previous version is completed as intended and let us know if you experience any further issues.
