### ISSUE TITLE
@open-wc/testing-helpers oneEvent TS errors after upgrade to 4.0.0

### ISSUE THREAD

**Issue by driesva** [open-wc/open-wc#2746]
## Actual Behavior

When upgrading to @open-wc/testing 4.0.0 we encounter following TypeScript errors in our tests:

```
error TS2554: Expected 3 arguments, but got 2.

        const event = oneEvent(fooFixture, 'barEventType') as Promise<BarEvent>;
                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  node_modules/@open-wc/testing-helpers/types/src/helpers.d.ts:85:112
    85 export function oneEvent<TEvent extends Event = CustomEvent<any>>(eventTarget: EventTarget, eventName: string, preventDefault: boolean): Promise<TEvent>;
                                                                                                                      ~~~~~~~~~~~~~~~~~~~~~~~
    An argument for 'preventDefault' was not provided.
```

I guess in [types.d.ts](https://github.com/open-wc/open-wc/blob/9767b1ae8a52424e224d238784e04a9710d4e9b3/packages/testing-helpers/src/types.d.ts#L2) it should rather be:

```
export type OneEventFn =
  <TEvent extends Event = CustomEvent>(eventTarget: EventTarget, eventName: string)=> Promise<TEvent>
```
(so no `preventDefault` argument)

given the functions in [helpers.js](https://github.com/open-wc/open-wc/blob/9767b1ae8a52424e224d238784e04a9710d4e9b3/packages/testing-helpers/src/helpers.js#L126) look like:

`export function oneEvent(eventTarget, eventName)`

and 

`export function oneDefaultPreventedEvent(eventTarget, eventName)`

## Additional context

We are using TypeScript 5.2.2 and Node 21.0.0

If someone confirms, we might open a PR if desired

**Comment by Didel** [comment]
@driesva I thought it was just me... I experienced te same after upgrading to 4.0.0. I decided to revert the upgrade, so a solution is more than welcome :)

**Comment by sbeemster-cs** [comment]
We ran into the exact same issue, and also decided to revert the update for now.

It seems to be a problem with the generated `helpers.d.ts`, which contains this weird definition:
```ts
/**
 * Registers a new element with an automatically generated unique name.
 * Helps to make a test fully isolated.
 *
 * @example
 * const tag = defineCE(class extends MyMixin(HTMLElement) {
 *   // define custom element class body
 * });
 * const el = fixture(`<${tag}></${tag}>`);
 * // test el
 *
 * @template {HTMLElement} T
 * @param {import("@open-wc/dedupe-mixin").Constructor<T>} klass Class which extends HTMLElement
 * @returns {string} Tag name of the registered element
 */
export function oneEvent<TEvent extends Event = CustomEvent<any>>(eventTarget: EventTarget, eventName: string, preventDefault: boolean): Promise<TEvent>;
```

The actual code in `helpers.js` looks perfectly fine.

**Comment by michaelwarren1106** [comment]
same issue, going to bump PR
