### ISSUE TITLE
[@import-maps/resolve] Can't import @import-maps/resolve/src/parser in TypeScript

### ISSUE THREAD

**Issue by stephenwade** [open-wc/open-wc#1987]
## Expected behavior

I should be able to use the following `import` statement in TypeScript:

```
import { ImportMap } from '@import-maps/resolve/src/parser';
```

## Actual Behavior

I get an error when trying to build the project:

```
$ yarn build
yarn run v1.22.10
$ rimraf packages/*/tsconfig.tsbuildinfo && tsc --build
packages/dev-server-import-maps/src/importMapsPlugin.ts:37:27 - error TS7016:
Could not find a declaration file for module '@import-maps/resolve/src/parser'.
'/Users/stephen/git/web/node_modules/@import-maps/resolve/src/parser.js'
implicitly has an 'any' type.
  Try `npm install @types/import-maps__resolve` if it exists or add a new
declaration (.d.ts) file containing `declare module '@import-maps/resolve/src/parser';`

37 import { ImportMap } from '@import-maps/resolve/src/parser';
                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Found 1 error.

error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

## Additional context

This was probably caused by #1949. The issue happens when updating @import-maps/resolve from 1.0.0 to 1.0.1:
https://github.com/modernweb-dev/web/pull/948

**Comment by stephenwade** [comment]
Fixed by:

```ts
import { ImportMap } from '@import-maps/resolve';
```

**Comment by LarsDenBakker** [comment]
Didn't notice this issue, but indeed just ran into the same problem :)
